name: Lint

on:
    push:
        branches: [main]
    pull_request:

jobs:
    run_tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.13.5

            - name: Install uv
              uses: astral-sh/setup-uv@v6

            - name: Install dependencies
              run: |
                  uv sync --frozen --no-install-project --no-dev --python-preference=only-system

            - name: Lint
              run: |
                  uv run flake8 $(find . -path ./.venv -prune -o -name "*.py" -print) --count --select=E9,F63,F7,F82 --show-source --statistics
                  uv run flake8 $(find . -path ./.venv -prune -o -name "*.py" -print) --count --exit-zero --max-complexity=10 --max-line-length=150 --statistics
                  uv run pylint $(find . -path ./.venv -prune -o -name "*.py" -print)
